site_name: Finance Starter Pack
site_favicon: graphics/favicon.ico
pages:
    - Home: index.md
    - Getting Started: gettingstarted.md
    - Architecture: architecture.md
    - Have a Play: play.md
    - IEX: iex.md
copyright: 'Copyright &copy 2016 Data Intellect Limited.  Kx &reg and kdb+ are registered trademarks of Kx Systems Inc.'

theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/AquaQAnalytics/TorQ-Finance-Starter-Pack'
extra:
   logo: 'graphics/TorQ-logo.png'
   palette:
      primary: 'indigo'
      accent: 'green'
   author:
      github: 'AquaQAnalytics'
      twitter: 'data_intellect'

google_analytics:
   - 'UA-51911331-4'
   - 'auto'
